name: GitHub Profile Review
description: Please review my GitHub profile on a livestream
title: "[REVIEW] <your-username>"
labels: [gh profile review, live stream review]
assignees:
- anshumanjadiya1102
body:
  - type: input
    id: link
    attributes:
      label: GitHub Profile Link
      placeholder: https://github.com/<your-username>
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Join our Discord Community [
        Follow us on LinkedIn
        Follow us on Twitter
        Feel free to check out other cool repositories 
