name: Open Source Project Review
description: Please review my project on a livestream
title: "[REVIEW] <project name here>"
labels: [open source review, live stream review]
assignees:
- anshumanjadiya1102
body:
  - type: markdown
    attributes:
      value: "Your project doesn't have to be hosted at GitHub, it can also be on GitLab or other VCS"
  - type: input
    id: link
    attributes:
      label: Project link
      placeholder: https://github.com/<your-username>/<project-name>
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Join our Discord Community
        Follow us on LinkedIn 
        Follow us on Twitter
        Feel free to check out other cool repositories
