name: Portfolio Review
description: Please review my Portfolio on a livestream
title: "[REVIEW]"
labels: [portfolio review, live stream review]
body:
  - type: markdown
    attributes:
      value: "**Please ensure that you don't have any personal details in your Portfolio that you don't want to share publicly.**"
  - type: input
    id: link
    attributes:
      label: Portfolio link
      placeholder: "e.g.: https://<your-username>.github.io/portfolio"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Join our Discord Community 
        Follow us on LinkedIn 
        Follow us on Twitter 
        Feel free to check out other cool repositories
